name: Robots4Life
favicon: null
layout_spectrum: 0.5837108113337308
typography_spectrum: 0.2572180638089776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.296444833278656
  lightness: 0.782713723834604
  saturation: 0.35215949499979615
  rhythmicContrast: 0.19392757350578904
purpose: []
